### ISSUE TITLE
Missing dinamically generated elements when going back in history

### ISSUE THREAD

**Issue by FerMod** [FerMod/ProyectoSW#6]
When going back in history does not load the image preview and the remove image button.

**Comment by FerMod** [comment]
This will be fixed when we learn to work with cookies

**Comment by FerMod** [comment]
Using AJAX, this is fixed, because it does not need to reload the page.
No need for cookies
🍪🍪🍪🍪🍪🍪⁽ˢʰᵃᵐᵉ···⁾

**Comment by micheldevs** [comment]
Dame esas galletas.
